<script>
require(['Global'], function(Global) {
    let fieldset = document.querySelector('fieldset');
    let inputs = fieldset.querySelectorAll('input, textarea');
    let inputHolder = Array.from(document.querySelectorAll(
        '.container .to-contact .contact fieldset .input-holder'));

    // Track the currently clicked input
    let clickedInput = null;

    document.addEventListener('click', (event) => {
        // Check if the clicked element is an input or its descendant
        let isInputClick = Array.from(inputs).some(input => input.contains(event.target));

        // If the click is not on an input or its descendant, remove the added style from all labels
        if (!isInputClick) {
            inputHolder.forEach(input => {
                let label = input.querySelector('label');
                label.style.cssText = '';
            });
            clickedInput = null;
        }

        // If the click is on an inputHolder or its descendant, make the label red for the clicked input
        let isInputHolderClick = inputHolder.some(input => input.contains(event.target));
        if (isInputHolderClick) {
            let label = event.target.closest('.input-holder').querySelector('label');
            label.style.cssText = 'transform:translate(0px,-14px);color: #FE6717;font-size: 13px';

            // Store the clicked input for tracking
            clickedInput = event.target.closest('.input-holder').querySelector('input');
        }
    });

    // Remove the style when clicking on inputs directly
    inputs.forEach(input => {
        input.addEventListener('click', (event) => {
            // Check if the clicked input is different from the currently clicked input
            if (clickedInput && clickedInput !== event.target) {
                inputHolder.forEach(input => {
                    let label = input.querySelector('label');
                    label.style.cssText = '';
                });
                clickedInput = null;
            }
        });
    });
});
</script>


<section class='container'>

    <div class='to-contact'>

        <form class="contact" action="<?= $block->escapeUrl($block->getFormAction()) ?>" id="contact-form" method="post"
            data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
            data-mage-init='{"validation":{}}'>
            <div>
                <legend><span><?= $block->escapeHtml(__('CONTACT US')) ?></span></legend><br />
                <br><br>
                <div class="sentence">
                    <?= $block->escapeHtml(__('Have something to say? Drop us a message and we’ll Get back to you soon')) ?>
                </div>
            </div>
            <fieldset>
                <div class='contact-one'>
                    <div class='input-holder'>
                        <label for="name"><span><?= $block->escapeHtml(__('Your Name')) ?></span></label>
                        <div>
                            <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Your Name')) ?>"
                                value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>"
                                type="text" data-validate="{required:true}" />
                        </div>
                    </div>
                    <div class='input-holder'>
                        <label for='email' class="label"
                            for="email"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
                        <div>
                            <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email Address')) ?>"
                                value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>"
                                type="email" data-validate="{required:true, 'validate-email':true}" />
                        </div>
                    </div>
                    <div class='input-holder'>
                        <label for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                        <div>
                            <input name="telephone" id="telephone"
                                title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                                value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>"
                                type="text" />
                        </div>
                    </div>
                </div>

                <div class='input-holder'>
                    <label for="comment"><span><?= $block->escapeHtml(__('Your Message')) ?></span></label>
                    <div>
                        <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Your Message')) ?>"
                            cols="5" rows="3"
                            data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
                    </div>

                    <div class="actions-toolbar">
                        <div>
                            <input type="hidden" name="hideit" id="hideit" value="" />
                            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>">
                                <span><?= $block->escapeHtml(__('send')) ?></span>
                            </button>
                        </div>


                    </div>
                    <?= $block->getChildHtml('form.additional.info') ?>
            </fieldset>

    </div>
    </form>
    </div>



</section>