<?php

/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$_product    = $block->getProduct();






$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)) : ?>
<?php foreach ($_attributes as $_attribute) : ?>

<div class="field configurable required">
    <label class="label" for="attribute<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>">
        <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
    </label>
    <div class="control">

        <select name="super_attribute[<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>]"
            data-selector="super_attribute[<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>]"
            data-validate="{required:true}" id="attribute<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>"
            class="super-attribute-select mySelect">
            <option value="">
                <?= $block->escapeHtml(__('Choose an Option...')) ?></option>
        </select>

        <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $bla = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                $att = $bla->getConfigurableAttributesAsArray($_product);


                foreach ($att as $i => $pr) {
                    foreach ($pr["values"] as $n) {


                ?>

        <div class='model-type' id=<?= $n['value_index']; ?>
            onclick="selectOption(<?= $block->escapeHtmlAttr($n['value_index']); ?>)">
            <?php echo  $n['label']; ?>
        </div>


        <?php
                    }
                }
                ?>

    </div>
</div>
<?php endforeach; ?>

<script>
function selectOption(optionValue) {
    // Get the select element
    var selectElement = document.querySelector(".mySelect");

    // Find the option element based on its value
    var optionElement = Array.from(selectElement.options).find(function(option) {
        return option.value == optionValue;
    });


    // Get the index of the option element
    var optionIndex = Array.from(selectElement.options).indexOf(optionElement);


    // Set the selected index
    selectElement.selectedIndex = optionIndex;

    selectElement.dispatchEvent(new Event('change'));
}
</script>

<script type="text/x-magento-init">
    {
            "#product_addtocart_form": {
                "configurable": {
                    "spConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                    "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar(
                                                    'gallery_switch_strategy',
                                                    'Magento_ConfigurableProduct'
                                                ) ?: 'replace'); ?>"
                }
            },
            "*" : {
                "Magento_ConfigurableProduct/js/catalog-add-to-cart": {}
            }
        }
    </script>
<?php endif; ?>