<section class='container'>

    <div class='centerize-Element'>

        <?php echo $this->getChildHtml('breadcrumbs'); ?>

        <div class='d-flex product-holder'>
            <?php echo $this->getChildHtml('product.info.media'); ?>




            <div class='product-container'>

                <?php echo $this->getChildHtml('product.info.main'); ?>
                <!-- <h2></h2>
                <p>Default#: <span></span></p> -->

            </div>





        </div>

    </div>

</section>